version: '1'
volumes:
  data:
services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mysecretpassword
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8001:80"
    environment:
      - PMA_ARBITRARY=1
